name = "NVIDIA Nemotron Nano 12B v2 VL BF16"
base_model = "nvidia/nemotron-nano-12b-v2-vl"
reasoning = false
structured_output = true

[cost]
input = 0.20
output = 0.60

[limit]
output = 8_192

[modalities]
input = ["text", "image"]
